logging: converting every possible "print" into log, Closes #9
Used loglevels:
error: for errors
info: for information that might be useful besides operating the program
debug: most data that is handled, and entering, leaving logical segments
  of the algorithm

This handles currently shown information, but need to add more logs.